export function generatePlanPDF(profile: any, workoutData: any, mealData: any) {
  // Create HTML content for PDF
  const htmlContent = `
    <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
      <h1>Fitness Plan - ${profile.name}</h1>
      <p><strong>Date Generated:</strong> ${new Date().toLocaleDateString()}</p>
      
      <h2>Profile Information</h2>
      <p><strong>Age:</strong> ${profile.age}</p>
      <p><strong>Weight:</strong> ${profile.weight} kg</p>
      <p><strong>Height:</strong> ${profile.height} cm</p>
      <p><strong>Fitness Level:</strong> ${profile.fitnessLevel}</p>
      <p><strong>Goal:</strong> ${profile.goal}</p>
      <p><strong>Training Days:</strong> ${profile.daysPerWeek} days/week</p>
      
      <h2>Workout Plan</h2>
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
        <tr style="background-color: #f0f0f0;">
          <th style="border: 1px solid #ddd; padding: 10px;">Day</th>
          <th style="border: 1px solid #ddd; padding: 10px;">Focus</th>
          <th style="border: 1px solid #ddd; padding: 10px;">Duration</th>
          <th style="border: 1px solid #ddd; padding: 10px;">Intensity</th>
        </tr>
        ${workoutData
          .map(
            (w: any) =>
              `<tr>
          <td style="border: 1px solid #ddd; padding: 10px;">${w.day}</td>
          <td style="border: 1px solid #ddd; padding: 10px;">${w.focus}</td>
          <td style="border: 1px solid #ddd; padding: 10px;">${w.duration}</td>
          <td style="border: 1px solid #ddd; padding: 10px;">${w.intensity}</td>
        </tr>`,
          )
          .join("")}
      </table>
      
      <h2>Meal Plan</h2>
      <p><strong>Daily Calories:</strong> ~1900 kcal</p>
      <p><strong>Protein Target:</strong> ~160g</strong></p>
      <p><strong>Carbs Target:</strong> ~200g</p>
      <p><strong>Fat Target:</strong> ~60g</p>
      
      <p style="margin-top: 40px; font-size: 12px; color: #999;">
        Generated by Fitness Plan Generator
      </p>
    </div>
  `

  // Use browser's print functionality
  const printWindow = window.open("", "_blank")
  if (printWindow) {
    printWindow.document.write(htmlContent)
    printWindow.document.close()
    printWindow.print()
  }
}

export function downloadPlanAsHTML(profile: any, workoutData: any, mealData: any) {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <title>Fitness Plan - ${profile.name}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; color: #333; line-height: 1.6; }
          h1 { color: #0ea5e9; }
          h2 { color: #0ea5e9; margin-top: 30px; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
          th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
          th { background-color: #f0f0f0; }
          .section { margin-bottom: 30px; }
          .footer { margin-top: 50px; font-size: 12px; color: #999; }
        </style>
      </head>
      <body>
        <h1>Fitness Plan - ${profile.name}</h1>
        <p><strong>Date Generated:</strong> ${new Date().toLocaleDateString()}</p>
        
        <div class="section">
          <h2>Profile Information</h2>
          <p><strong>Age:</strong> ${profile.age}</p>
          <p><strong>Weight:</strong> ${profile.weight} kg</p>
          <p><strong>Height:</strong> ${profile.height} cm</p>
          <p><strong>Fitness Level:</strong> ${profile.fitnessLevel}</p>
          <p><strong>Goal:</strong> ${profile.goal}</p>
          <p><strong>Training Days:</strong> ${profile.daysPerWeek} days/week</p>
        </div>
        
        <div class="section">
          <h2>Workout Plan</h2>
          <table>
            <tr>
              <th>Day</th>
              <th>Focus</th>
              <th>Duration</th>
              <th>Intensity</th>
            </tr>
            ${workoutData
              .map(
                (w: any) =>
                  `<tr>
              <td>${w.day}</td>
              <td>${w.focus}</td>
              <td>${w.duration}</td>
              <td>${w.intensity}</td>
            </tr>`,
              )
              .join("")}
          </table>
        </div>
        
        <div class="section">
          <h2>Meal Plan Summary</h2>
          <p><strong>Daily Calories:</strong> ~1900 kcal</p>
          <p><strong>Protein Target:</strong> ~160g</p>
          <p><strong>Carbs Target:</strong> ~200g</p>
          <p><strong>Fat Target:</strong> ~60g</p>
        </div>
        
        <div class="footer">
          <p>Generated by Fitness Plan Generator</p>
        </div>
      </body>
    </html>
  `

  const element = document.createElement("a")
  element.setAttribute("href", "data:text/html;charset=utf-8," + encodeURIComponent(htmlContent))
  element.setAttribute("download", `fitness-plan-${profile.name}-${Date.now()}.html`)
  element.style.display = "none"
  document.body.appendChild(element)
  element.click()
  document.body.removeChild(element)
}
